blank_issues_enabled: false
contact_links:
  - name: â“ Questions & Help
    url: https://github.com/shopstr-eng/shopstr/discussions
    about: Please ask and answer questions here
  - name: ğŸ’¬ Chat & Discussion
    url: https://github.com/shopstr-eng/shopstr/discussions
    about: Join the conversation    
